# Codex-rs Cargo Build Configuration
# 
# This configuration ensures stable builds across different environments
# and prevents CPU instruction set related build errors.

[build]
# Use generic x86-64 instruction set to avoid ILLEGAL_INSTRUCTION errors
rustflags = ["-C", "target-cpu=x86-64"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=x86-64"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=x86-64"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=x86-64"]

# Optional: Increase parallel jobs (uncomment if needed)
# [build]
# jobs = 8

# Optional: Incremental compilation (default: true for debug, false for release)
# [build]
# incremental = true
